version: 0.2

env:
  secrets-manager:
    LOGIN: dev/sonar:sonartoken
    HOST: dev/sonar:HOST
    Organization: dev/sonar:Organization
    Project: dev/sonar:Project

  variables:
    # ---------------------------------------------------
    # 📌 FIXED TOOL DOWNLOAD URLS
    # ---------------------------------------------------
    SONAR_SCANNER_URL: "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.3.0.5189-linux-x64.zip"
    TRIVY_URL: "https://github.com/aquasecurity/trivy/releases/download/v0.67.2/trivy_0.67.2_Linux-64bit.tar.gz"
    DEP_CHECK_URL: "https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.9/dependency-check-12.1.9-release.zip"

    # Docker Repo
    IMAGE_REPO_NAME: "zomato"
    IMAGE_TAG: ""

    # SCA fail threshold (optional)
    DEP_CHECK_FAIL_CVSS: ""

    # If true, Trivy image scan will return non-zero exit code when HIGH/CRITICAL findings exist.
    # Set to "true" to fail the build on HIGH/CRITICAL image findings; "false" to only report.
    TRIVY_FAIL_IMAGE: "false"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase..."
      - aws --version || true

  pre_build:
    commands:
      - echo "Pre-build phase..."
      - |
        if command -v apt-get >/dev/null 2>&1; then
          apt-get update -y
          apt-get install -y jq curl unzip wget default-jre docker.io
        elif command -v yum >/dev/null 2>&1; then
          yum install -y jq curl unzip wget java-11-openjdk docker
        else
          echo "Ensure Java, unzip, curl, wget, docker installed"
        fi
      - echo "Ensure Docker daemon is running (if applicable)..."
      - docker --version || true

      # -----------------------------
      # Install SonarScanner
      # -----------------------------
      - echo "Downloading SonarScanner..."
      - wget -q "$SONAR_SCANNER_URL" -O sonar-scanner.zip
      - unzip -q sonar-scanner.zip
      - SCANNER_DIR=$(ls -d sonar-scanner-* | head -n1)
      - chmod +x "$SCANNER_DIR/bin/sonar-scanner"
      - export PATH="$PWD/$SCANNER_DIR/bin:$PATH"
      - sonar-scanner --version || true

  build:
    commands:
      - echo "Build phase..."

      # -----------------------------
      # INSTALL DEPENDENCIES
      # -----------------------------
      - echo "Installing NodeJS dependencies..."
      - npm install --legacy-peer-deps || npm install

      # -----------------------------
      # OWASP DEPENDENCY CHECK
      # -----------------------------
      - echo "Downloading Dependency-Check..."
      - mkdir -p dependency-check-reports
      - wget -q "$DEP_CHECK_URL" -O depcheck.zip
      - unzip -q depcheck.zip
      - DCPATH=$(ls -d dependency-check-* | head -n1)
      - chmod +x "${DCPATH}/bin/dependency-check.sh"

      - |
        echo "Running Dependency-Check SCA..."
        DC_ARGS="--project ${IMAGE_REPO_NAME} --scan . --out dependency-check-reports --format ALL"


        if [ -n "$DEP_CHECK_FAIL_CVSS" ]; then
          DC_ARGS="$DC_ARGS --failOnCVSS $DEP_CHECK_FAIL_CVSS"
        fi

        set +e
        "${DCPATH}/bin/dependency-check.sh" $DC_ARGS
        DC_EXIT=$?
        set -e

        if [ $DC_EXIT -ne 0 ]; then
          if [ -n "$DEP_CHECK_FAIL_CVSS" ]; then
            echo "Failing build due to Dependency-Check CVSS threshold"
            exit $DC_EXIT
          else
            echo "Continuing despite Dependency-Check findings"
          fi
        fi

      # -----------------------------
      # SONARQUBE SCAN
      # -----------------------------
      - echo "Running SonarScanner..."
      - |
        sonar-scanner \
          -Dsonar.login="$LOGIN" \
          -Dsonar.host.url="$HOST" \
          -Dsonar.projectKey="$Project" \
          -Dsonar.organization="$Organization" \
          2>&1 | tee sonar-output.txt

      - sleep 10
      - curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project" > result.json || true

      - |
        if [ -f result.json ] && [ "$(jq -r '.projectStatus.status' result.json 2>/dev/null)" = "ERROR" ]; then
          echo "Sonar Quality Gate FAILED"
          exit 1
        else
          echo "Sonar Quality Gate passed or not present"
        fi

      # -----------------------------
      # PREP DOCKER DETAILS
      # -----------------------------
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - |
        if [ -z "$IMAGE_TAG" ]; then
          IMAGE_TAG="${CODEBUILD_BUILD_NUMBER:-$(date +%Y%m%d%H%M%S)}"
        fi
      - export IMAGE_TAG

      - IMAGE_FULLNAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}"
      - echo "Image full name: ${IMAGE_FULLNAME}"

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION \
        | docker login --username AWS --password-stdin \
          ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

      - aws ecr describe-repositories --repository-names ${IMAGE_REPO_NAME} \
        || aws ecr create-repository --repository-name ${IMAGE_REPO_NAME}

      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${IMAGE_FULLNAME}

  post_build:
    commands:
      - echo "Post-build: run image scan before push"

      # -----------------------------
      # INSTALL TRIVY FIXED VERSION
      # -----------------------------
      - echo "Installing Trivy from: $TRIVY_URL"
      - wget -q "$TRIVY_URL" -O trivy.tar.gz
      - tar -xzf trivy.tar.gz || true
      # trivy binary may unpack as 'trivy' in working dir; handle idempotently
      - if [ -f trivy ]; then chmod +x trivy && mv -f trivy /usr/local/bin/ || true; fi
      - if [ -f trivy-*-linux-amd64 ]; then mv -f trivy-*-linux-amd64 /usr/local/bin/trivy || true; fi
      - trivy --version || true

      # -----------------------------
      # TRIVY FILESYSTEM SCAN (source)
      # -----------------------------
      - mkdir -p trivy-reports
      - |
        echo "Starting Trivy filesystem scan (HIGH,CRITICAL)..."
        set +e
        trivy filesystem . \
          --format json \
          --severity HIGH,CRITICAL \
          --output trivy-reports/trivy-filesystem.json \
          --exit-code 0
        trivy filesystem . \
          --format sarif \
          --severity HIGH,CRITICAL \
          --output trivy-reports/trivy-filesystem.sarif \
          --exit-code 0
        trivy filesystem . --format table --severity HIGH,CRITICAL --exit-code 0 || true
        set -e
        echo "Trivy filesystem scan completed."

      # -----------------------------
      # TRIVY IMAGE (LOCAL) SCAN — BEFORE PUSH
      # -----------------------------
      - |
        echo "Starting Trivy image scan for local image: ${IMAGE_REPO_NAME}:${IMAGE_TAG} (HIGH,CRITICAL)..."
        set +e

        # default behavior: do not fail the build on findings (exit-code 0)
        TRIVY_EXIT_CODE_FLAG="--exit-code 0"
        if [ "${TRIVY_FAIL_IMAGE}" = "true" ]; then
          # Exit code 1 when any vulnerabilities of selected severity are found
          TRIVY_EXIT_CODE_FLAG="--exit-code 1"
          echo "TRIVY_FAIL_IMAGE is true -> build will fail if HIGH/CRITICAL findings are present."
        fi

        # JSON output
        trivy image "${IMAGE_REPO_NAME}:${IMAGE_TAG}" \
          --format json \
          --severity HIGH,CRITICAL \
          --output trivy-reports/trivy-image.json \
          $TRIVY_EXIT_CODE_FLAG
        TRIVY_IMG_EXIT=$?

        # SARIF output
        trivy image "${IMAGE_REPO_NAME}:${IMAGE_TAG}" \
          --format sarif \
          --severity HIGH,CRITICAL \
          --output trivy-reports/trivy-image.sarif \
          --exit-code 0 || true

        # Table summary to stdout (non-failing)
        trivy image "${IMAGE_REPO_NAME}:${IMAGE_TAG}" --format table --severity HIGH,CRITICAL --exit-code 0 || true

        set -e
        if [ $TRIVY_IMG_EXIT -ne 0 ]; then
          if [ "${TRIVY_FAIL_IMAGE}" = "true" ]; then
            echo "Trivy found HIGH/CRITICAL vulnerabilities in image and TRIVY_FAIL_IMAGE=true -> failing build."
            exit $TRIVY_IMG_EXIT
          else
            echo "Trivy found HIGH/CRITICAL vulnerabilities in image (reported), but TRIVY_FAIL_IMAGE=false -> continuing."
          fi
        else
          echo "Trivy image scan passed (no HIGH/CRITICAL findings according to exit-code policy)."
        fi

      # -----------------------------
      # PUSH IMAGE TO ECR (after scan)
      # -----------------------------
      - |
        echo "Pushing Docker image to ECR: ${IMAGE_FULLNAME}"
        docker push ${IMAGE_FULLNAME} || echo "Docker push failed (check auth/permissions)"

      - echo "Post build done. Listing reports:"
      - ls -la trivy-reports/ || true
      - ls -la dependency-check-reports/ || true

artifacts:
  files:
    - sonar-output.txt
    - result.json
    - trivy-reports/**
    - dependency-check-reports/**
  discard-paths: no
