version: 0.2

env:
  variables:
    INSPECT_DIR: "/tmp/inspections"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "== START install phase =="
      - mkdir -p $INSPECT_DIR
      - date > $INSPECT_DIR/build_start_time.txt
  pre_build:
    commands:
      - echo "== PRE_BUILD: collect basic info =="
      - echo "OS release:" > $INSPECT_DIR/os-release.txt || true
      - cat /etc/os-release >> $INSPECT_DIR/os-release.txt 2>/dev/null || true
      - uname -a > $INSPECT_DIR/uname.txt || true
      - lscpu > $INSPECT_DIR/lscpu.txt || true
      - cat /proc/meminfo > $INSPECT_DIR/proc-meminfo.txt || true
      - free -m > $INSPECT_DIR/free-m.txt || true
      - df -h > $INSPECT_DIR/df-h.txt || true
      - df -i > $INSPECT_DIR/df-i.txt || true
      - lsblk > $INSPECT_DIR/lsblk.txt || true
      - mount > $INSPECT_DIR/mounts.txt || true
      - ps aux --sort=-%mem | head -n 50 > $INSPECT_DIR/top-procs.txt || true
      - env > $INSPECT_DIR/env.txt || true
      - echo "Checking package manager and listing top packages" > $INSPECT_DIR/packages.txt
      - if command -v rpm >/dev/null 2>&1; then echo "RPM-based system detected" >> $INSPECT_DIR/packages.txt && rpm -qa | head -n 200 >> $INSPECT_DIR/packages.txt; fi
      - if command -v dpkg >/dev/null 2>&1; then echo "DEB-based system detected" >> $INSPECT_DIR/packages.txt && dpkg -l | head -n 200 >> $INSPECT_DIR/packages.txt; fi
      - echo "Docker info (if available):" > $INSPECT_DIR/docker.txt || true
      - if command -v docker >/dev/null 2>&1; then docker info >> $INSPECT_DIR/docker.txt 2>&1 || true && docker images >> $INSPECT_DIR/docker.txt 2>&1 || true; fi
      - echo "Listing /etc for inspection" > $INSPECT_DIR/etc-list.txt && ls -la /etc | head -n 200 >> $INSPECT_DIR/etc-list.txt || true
  build:
    commands:
      - echo "== BUILD phase (placeholder) =="
      - echo "You can insert your build steps here..."
  post_build:
    commands:
      - echo "== POST_BUILD: finalizing reports =="
      - date >> $INSPECT_DIR/build_end_time.txt
      - echo "Created inspection files:"
      - ls -la $INSPECT_DIR || true

artifacts:
  files:
    - '/tmp/inspections/**'
  discard-paths: no
