version: 0.2

env:
  secrets-manager:
    LOGIN: dev/sonar:sonartoken
    HOST: dev/sonar:HOST
    Organization: dev/sonar:Organization
    Project: dev/sonar:Project

  variables:
    SONAR_ZIP_URL: "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.3.0.5189-linux-x64.zip"
    DEP_CHECK_ZIP_URL: "https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.9/dependency-check-12.1.9-release.zip"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase ..."

  pre_build:
    commands:
      - echo "Pre build phase ..."
      - |
        echo "Working dir: $(pwd)"      
      - |
        # Install system dependencies
        if command -v apt-get >/dev/null 2>&1; then
          apt-get update -y
          apt-get install -y --no-install-recommends jq curl unzip wget default-jre-headless
        elif command -v yum >/dev/null 2>&1; then
          yum install -y jq curl unzip wget java-11-openjdk-headless
        else
          echo "No apt-get/yum found; ensure jq/curl/unzip/wget/java are present in the image"
        fi
      - |
        # Verify Java installation for Dependency-Check
        echo "Checking Java installation..."
        java -version || echo "Java version check failed"
        if ! command -v java >/dev/null 2>&1; then
          echo "WARNING: Java is required for Dependency-Check but not installed"
        fi
      - echo "Downloading SonarScanner..."
      - wget -q "$SONAR_ZIP_URL" -O sonar-scanner.zip || curl -sSL "$SONAR_ZIP_URL" -o sonar-scanner.zip
      - unzip -q sonar-scanner.zip
      - SCANNER_DIR=$(ls -d sonar-scanner-* 2>/dev/null | head -n1)
      - |
        if [ -z "$SCANNER_DIR" ]; then
          echo "ERROR: sonar scanner directory not found after unzip"
          ls -la
          exit 1
        fi
      - chmod +x "$SCANNER_DIR/bin/sonar-scanner"
      - export PATH="$PWD/$SCANNER_DIR/bin:$PATH"
      - |
        echo "sonar-scanner path: $(which sonar-scanner || echo 'not found')"
      - sonar-scanner --version || echo "sonar-scanner version check failed (continuing)"
      - echo "Pre-build setup complete"

  build:
    commands:
      - echo "Build phase ..."
      - sonar-scanner -Dsonar.login="$LOGIN" -Dsonar.host.url="$HOST" -Dsonar.projectKey="$Project" -Dsonar.organization="$Organization" 2>&1 | tee sonar-output.txt
      - sleep 10
      - curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project" > result.json || true
      - cat result.json || true
      - |
        if [ "$(jq -r '.projectStatus.status' result.json 2>/dev/null)" = "ERROR" ]; then
          echo "Quality Gate failed! Build will be marked as failed."
          exit 1
        else
          echo "Quality Gate passed or not present."
        fi

  post_build:
    commands:
      - |
        echo "=== Post build phase: OWASP Dependency-Check v12.1.9 ==="
      - |
        echo "Checking for dependency files to scan..."
        find . -name "package.json" -o -name "pom.xml" -o -name "build.gradle" -o -name "*.csproj" -o -name "requirements.txt" | head -10 || echo "No common dependency files found (this may be normal)"
      - |
        echo "Downloading Dependency-Check..."
        if wget -q "$DEP_CHECK_ZIP_URL" -O dependency-check.zip; then
          echo "Download via wget successful"
        elif curl -sSL "$DEP_CHECK_ZIP_URL" -o dependency-check.zip; then
          echo "Download via curl successful"
        else
          echo "ERROR: Failed to download Dependency-Check from $DEP_CHECK_ZIP_URL"
          echo "Skipping Dependency-Check analysis"
          exit 0
        fi
      - |
        if [ -f dependency-check.zip ]; then
          echo "Unzipping Dependency-Check..."
          if unzip -q dependency-check.zip; then
            DEP_DIR=$(ls -d dependency-check-* 2>/dev/null | head -n1)
            if [ -n "$DEP_DIR" ] && [ -d "$DEP_DIR" ]; then
              echo "Dependency-Check directory found: $DEP_DIR"
              chmod +x "$DEP_DIR/bin/dependency-check.sh"
              export PATH="$PWD/$DEP_DIR/bin:$PATH"
              echo "Dependency-Check version check:"
              "$DEP_DIR/bin/dependency-check.sh" --version || echo "Version check failed"
            else
              echo "ERROR: Valid dependency-check directory not found after unzip"
              ls -la
              exit 0
            fi
          else
            echo "ERROR: Failed to unzip dependency-check.zip"
            exit 0
          fi
        else
          echo "dependency-check.zip not present; skipping dependency-check CLI"
          exit 0
        fi
      - |
        if command -v dependency-check.sh >/dev/null 2>&1; then
          echo "Running Dependency-Check scan..."
          # Create report directory first
          mkdir -p dependency-check-report
          
          # Run dependency check with specific formats and continue on error
          dependency-check.sh \
            --project "$Project" \
            --scan . \
            --format "HTML" "JSON" "XML" \
            --out ./dependency-check-report \
            --enableRetired \
            --failOnCVSS 0 \
            || echo "Dependency-Check completed with exit code: $? (continuing build)"
          
          echo "Dependency-Check reports location:"
          ls -la dependency-check-report/ || echo "No dependency-check-report directory created"
        else
          echo "ERROR: dependency-check.sh command not found in PATH"
          echo "PATH: $PATH"
          exit 0
        fi
      - |
        echo "=== Build Artifacts Summary ==="
        echo "Current directory contents:"
        ls -la
        echo "Dependency-Check report contents:"
        ls -la dependency-check-report/ || echo "No dependency-check-report directory"

artifacts:
  files:
    - sonar-output.txt
    - result.json
    - dependency-check-report/**/*
  discard-paths: no