version: 0.2

env:
  secrets-manager:
    LOGIN: dev/sonar:sonartoken
    HOST: dev/sonar:HOST
    Organization: dev/sonar:Organization
    Project: dev/sonar:Project

  variables:
    SONAR_ZIP_URL: "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.3.0.5189-linux-x64.zip"
    # Change IMAGE_REPO_NAME if required
    IMAGE_REPO_NAME: "zomato"
    # Optional: you can override IMAGE_TAG externally (e.g., CODEBUILD_RESOLVED_SOURCE_VERSION short sha)
    IMAGE_TAG: "" 

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase ..."
      - echo "Logging into ECR (will attempt later with dynamic account id)"
      - aws --version || true

  pre_build:
    commands:
      - echo "Pre build phase ..."
      - |
        echo "Working dir: $(pwd)"

      - |
        # Install utilities if package manager available
        if command -v apt-get >/dev/null 2>&1; then
          apt-get update -y
          apt-get install -y --no-install-recommends jq curl unzip wget
        elif command -v yum >/dev/null 2>&1; then
          yum install -y jq curl unzip wget
        else
          echo "No apt-get/yum found; ensure jq/curl/unzip/wget are present in the image"
        fi

      - echo "Downloading SonarScanner..."
      - wget -q "$SONAR_ZIP_URL" -O sonar-scanner.zip || curl -sSL "$SONAR_ZIP_URL" -o sonar-scanner.zip
      - unzip -q sonar-scanner.zip
      - SCANNER_DIR=$(ls -d sonar-scanner-* 2>/dev/null | head -n1)
      - |
        if [ -z "$SCANNER_DIR" ]; then
          echo "ERROR: sonar scanner directory not found after unzip"
          ls -la
          exit 1
        fi
      - chmod +x "$SCANNER_DIR/bin/sonar-scanner"
      - |
        export PATH="$PWD/$SCANNER_DIR/bin:$PATH"
      - |
        echo "sonar-scanner path: $(which sonar-scanner || echo 'not found')"
      - sonar-scanner --version || echo "sonar-scanner version check failed (continuing)"
      - echo "Pre-build setup complete"

  build:
    commands:
      - echo "Build phase ..."

      - |
        # Run SonarScanner
        echo "Running SonarScanner..."
        sonar-scanner -Dsonar.login="$LOGIN" \
                      -Dsonar.host.url="$HOST" \
                      -Dsonar.projectKey="$Project" \
                      -Dsonar.organization="$Organization" 2>&1 | tee sonar-output.txt || true

      - sleep 10
      - curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project" > result.json || true
      - cat result.json || true

      - |
        # Fail build if Sonar quality gate is ERROR
        if [ "$(jq -r '.projectStatus.status' result.json 2>/dev/null)" = "ERROR" ]; then
          echo "Quality Gate failed! Build will be marked as failed."
          exit 1
        else
          echo "Quality Gate passed or not present."
        fi

      - echo "Preparing Docker/ECR variables..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - |
        # If IMAGE_TAG variable was not provided, use CodeBuild short sha fallback
        if [ -z "$IMAGE_TAG" ]; then
          if [ -n "$CODEBUILD_RESOLVED_SOURCE_VERSION" ]; then
            IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
          else
            IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          fi
        fi
      - export IMAGE_TAG
      - IMAGE_REPO_NAME=${IMAGE_REPO_NAME}
      - export IMAGE_REPO_NAME
      - IMAGE_FULLNAME=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - export IMAGE_FULLNAME
      - echo "Image will be: ${IMAGE_FULLNAME}"

      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

      - echo "Ensure ECR repository exists..."
      - aws ecr describe-repositories --repository-names ${IMAGE_REPO_NAME} --region $AWS_DEFAULT_REGION || aws ecr create-repository --repository-name ${IMAGE_REPO_NAME} --region $AWS_DEFAULT_REGION

      - echo "Building Docker image..."
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .

      - echo "Tagging image..."
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${IMAGE_FULLNAME}

  post_build:
    commands:
      - echo "Post build phase: push image and run Trivy"

      - echo "Pushing Docker image to ECR: ${IMAGE_FULLNAME}"
      - docker push ${IMAGE_FULLNAME}

      - |
        echo "Installing Trivy..."
        set -e
        TRIVY_API_JSON="https://api.github.com/repos/aquasecurity/trivy/releases/latest"
        TRIVY_VERSION=$(curl -s $TRIVY_API_JSON | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' || echo "")
        if [ -z "$TRIVY_VERSION" ]; then
          echo "Could not detect Trivy latest version via GitHub API; attempting fallback to v0.57.0"
          TRIVY_VERSION="v0.57.0"
        fi
        echo "Using Trivy version: $TRIVY_VERSION"
        wget -q "https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${TRIVY_VERSION#v}_Linux-64bit.tar.gz" -O trivy.tar.gz || curl -sSL "https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${TRIVY_VERSION#v}_Linux-64bit.tar.gz" -o trivy.tar.gz
        tar -xzf trivy.tar.gz || true
        chmod +x trivy || true
        mv -f trivy /usr/local/bin/ || mkdir -p /usr/local/bin && mv -f trivy /usr/local/bin/ || true
        echo "Trivy version:"
        trivy --version || true
        set +e

      - |
        echo "Running Trivy filesystem scan..."
        mkdir -p trivy-reports
        trivy filesystem . \
          --format json \
          --output trivy-reports/trivy-filesystem.json \
          --severity HIGH,CRITICAL \
          --exit-code 0 || echo "Trivy filesystem scan completed with findings (non-zero exit code)"

        trivy filesystem . \
          --format sarif \
          --output trivy-reports/trivy-filesystem.sarif \
          --severity HIGH,CRITICAL \
          --exit-code 0 || true

        trivy filesystem . \
          --format table \
          --severity HIGH,CRITICAL \
          --exit-code 0 || true

        echo "Trivy filesystem scan completed. Reports in trivy-reports/"

      - |
        # Display summary of Trivy findings (if JSON exists)
        if [ -f "trivy-reports/trivy-filesystem.json" ]; then
          echo "=== Trivy Scan Summary ==="
          COUNT=$(jq '.Results | length' trivy-reports/trivy-filesystem.json 2>/dev/null || echo "0")
          VULNERABILITIES=$(jq '[.Results[].Vulnerabilities[]?] | length' trivy-reports/trivy-filesystem.json 2>/dev/null || echo "0")
          echo "Scanned targets: $COUNT"
          echo "Vulnerabilities found: $VULNERABILITIES"
          CRITICAL=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity == "CRITICAL")] | length' trivy-reports/trivy-filesystem.json 2>/dev/null || echo "0")
          HIGH=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity == "HIGH")] | length' trivy-reports/trivy-filesystem.json 2>/dev/null || echo "0")
          echo "CRITICAL: $CRITICAL"
          echo "HIGH: $HIGH"
        else
          echo "Trivy JSON report not found or empty"
        fi

      - echo "Post build complete. Listing files:"
      - ls -la
      - ls -la trivy-reports/ || true

artifacts:
  files:
    - sonar-output.txt
    - result.json
    - trivy-reports/**
  discard-paths: no
