version: 0.2

env:
  secrets-manager:
    LOGIN: dev/sonar:sonartoken
    HOST: dev/sonar:HOST
    Organization: dev/sonar:Organization
    Project: dev/sonar:Project

  variables:
    SONAR_ZIP_URL: "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.3.0.5189-linux-x64.zip"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase ..."

  pre_build:
    commands:
      - echo "Pre build phase ..."
      - |
        echo "Working dir: $(pwd)"      
      - |
        if command -v apt-get >/dev/null 2>&1; then
          apt-get update -y
          apt-get install -y --no-install-recommends jq curl unzip wget default-jre-headless
        elif command -v yum >/dev/null 2>&1; then
          yum install -y jq curl unzip wget java-11-openjdk-headless
        else
          echo "No apt-get/yum found; ensure jq/curl/unzip/wget/java are present in the image"
        fi
      - echo "Downloading SonarScanner..."
      - wget -q "$SONAR_ZIP_URL" -O sonar-scanner.zip || curl -sSL "$SONAR_ZIP_URL" -o sonar-scanner.zip
      - unzip -q sonar-scanner.zip
      - SCANNER_DIR=$(ls -d sonar-scanner-* 2>/dev/null | head -n1)
      - |
        if [ -z "$SCANNER_DIR" ]; then
          echo "ERROR: sonar scanner directory not found after unzip"
          ls -la
          exit 1
        fi
      - chmod +x "$SCANNER_DIR/bin/sonar-scanner"
      - export PATH="$PWD/$SCANNER_DIR/bin:$PATH"
      - |
        echo "sonar-scanner path: $(which sonar-scanner || echo 'not found')"
      - sonar-scanner --version || echo "sonar-scanner version check failed (continuing)"
      - echo "Pre-build setup complete"

  build:
    commands:
      - echo "Build phase ..."
      - sonar-scanner -Dsonar.login="$LOGIN" -Dsonar.host.url="$HOST" -Dsonar.projectKey="$Project" -Dsonar.organization="$Organization" 2>&1 | tee sonar-output.txt
      - sleep 10
      - curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project" > result.json || true
      - cat result.json || true
      - |
        if [ "$(jq -r '.projectStatus.status' result.json 2>/dev/null)" = "ERROR" ]; then
          echo "Quality Gate failed! Build will be marked as failed."
          exit 1
        else
          echo "Quality Gate passed or not present."
        fi

  post_build:
    commands:
      - echo "Post build phase complete"
      - echo "Listing files:"
      - ls -la

artifacts:
  files:
    - sonar-output.txt
    - result.json
  discard-paths: no